### ISSUE TITLE
Having issues when using comlink with react (storing in react state)

### ISSUE THREAD

**Issue by pycan-jouza** [GoogleChromeLabs/comlink#663]
Hi, i've been struggling for a few days already so decided to ask the community. I'd like to store the comlink wrapped worker in react state so that I can reuse it (I need to do it this way because the worker initialization is asynchronous and it needs to load before the UI). Here's the code:

worker.ts

```
import * as comlink from "comlink";
import sqlite3InitModule from "@sqlite.org/sqlite-wasm";

const initSqlite = async () => {
  try {
    const sqlite3 = await sqlite3InitModule();

    if (!("opfs" in sqlite3)) {
      throw new Error("OPFS not suppored");
    }

    const db = new sqlite3.oo1.OpfsDb("mydb.sqlite3", "ct");

    comlink.expose(db);

    self.postMessage({ type: "dbReady" });
  } catch (err) {
    console.error("Initialization error:", err);
  }
};

initSqlite();
```

DatabaseContext.tsx
```
  const [dbLoading, setDbLoading] = useState(true);
  const [workerApi, setWorkerApi] = useState();

  useEffect(() => {
    const worker = new Worker(new URL("./worker.ts", import.meta.url), {
      type: "module",
    });

    worker.onmessage = (ev) => {
      if (ev.data.type === "dbReady") {
        setDbLoading(false);

        const workerApi = comlink.wrap(worker);

        workerApi.selectObjects("select * from device").then(console.log); // this works just fine

        setWorkerApi(workerApi);
      }
    };
  }, []);
```

SomeComponent.tsx
```
  const { workerApi } = useDatabaseContext();

  useEffect(() => {
    workerApi.selectObjects("select * from categories").then(console.log); // this doesn't work
  }, [workerApi]);
```

SomeComponent only renders, when worker initialized.

This is what I see in the console.

```
comlink.mjs:64 Uncaught (in promise) TypeError: rawValue.apply is not a function
    at callback (comlink.mjs:116:48)
deserialize @ comlink.mjs:64
fromWireValue @ comlink.mjs:330
Promise.then (async)
apply @ comlink.mjs:268
basicStateReducer @ react-dom.development.js:11419
updateReducerImpl @ react-dom.development.js:11610
updateReducer @ react-dom.development.js:11447
updateState @ react-dom.development.js:11950
useState @ react-dom.development.js:13446
useState @ react.development.js:1750
DatabaseProvider @ DatabaseContext.tsx:31
renderWithHooks @ react-dom.development.js:11021
updateFunctionComponent @ react-dom.development.js:16184
beginWork$1 @ react-dom.development.js:18396
beginWork @ react-dom.development.js:26791
performUnitOfWork @ react-dom.development.js:25637
workLoopSync @ react-dom.development.js:25353
renderRootSync @ react-dom.development.js:25308
performConcurrentWorkOnRoot @ react-dom.development.js:24432
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
```

```
comlink.mjs:348 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': #<Promise> could not be cloned.
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/comlink/dist/esm/comlink.mjs:348:12)
    at new Promise (<anonymous>)
    at requestResponseMessage (webpack-internal:///(app-pages-browser)/./node_modules/comlink/dist/esm/comlink.mjs:336:12)
    at Object.apply (webpack-internal:///(app-pages-browser)/./node_modules/comlink/dist/esm/comlink.mjs:264:20)
    at basicStateReducer (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:11419:41)
    at updateReducerImpl (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:11610:11)
    at updateReducer (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:11447:10)
    at updateState (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:11950:10)
    at Object.useState (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:13446:16)
    at useState (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react/cjs/react.development.js:1750:21)
    at DatabaseProvider (webpack-internal:///(app-pages-browser)/./src/contexts/DatabaseContext.tsx:34:86)
    at renderWithHooks (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:11021:18)
    at updateFunctionComponent (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:16184:20)
    at beginWork$1 (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:18396:16)
    at beginWork (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:26791:14)
    at performUnitOfWork (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:25637:12)
    at workLoopSync (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:25353:5)
    at renderRootSync (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:25308:7)
    at performConcurrentWorkOnRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:24432:74)
    at workLoop (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:256:34)
    at flushWork (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:225:14)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:534:21)
eval @ comlink.mjs:348
requestResponseMessage @ comlink.mjs:336
apply @ comlink.mjs:264
basicStateReducer @ react-dom.development.js:11419
updateReducerImpl @ react-dom.development.js:11610
updateReducer @ react-dom.development.js:11447
updateState @ react-dom.development.js:11950
useState @ react-dom.development.js:13446
useState @ react.development.js:1750
DatabaseProvider @ DatabaseContext.tsx:31
renderWithHooks @ react-dom.development.js:11021
updateFunctionComponent @ react-dom.development.js:16184
beginWork$1 @ react-dom.development.js:18396
beginWork @ react-dom.development.js:26791
performUnitOfWork @ react-dom.development.js:25637
workLoopSync @ react-dom.development.js:25353
renderRootSync @ react-dom.development.js:25308
performConcurrentWorkOnRoot @ react-dom.development.js:24432
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
Promise.then (async)
apply @ comlink.mjs:268
basicStateReducer @ react-dom.development.js:11419
updateReducerImpl @ react-dom.development.js:11610
updateReducer @ react-dom.development.js:11447
updateState @ react-dom.development.js:11950
useState @ react-dom.development.js:13446
useState @ react.development.js:1750
DatabaseProvider @ DatabaseContext.tsx:31
renderWithHooks @ react-dom.development.js:11021
updateFunctionComponent @ react-dom.development.js:16184
beginWork$1 @ react-dom.development.js:18396
beginWork @ react-dom.development.js:26791
performUnitOfWork @ react-dom.development.js:25637
workLoopSync @ react-dom.development.js:25353
renderRootSync @ react-dom.development.js:25308
performConcurrentWorkOnRoot @ react-dom.development.js:24432
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
Show 38 more frames
```

```
react-dom.development.js:20702 Uncaught TypeError: workerApi.selectObjects is not a function
    at eval (Account.tsx:10:15)
    at commitHookEffectListMount (react-dom.development.js:21035:23)
    at invokePassiveEffectMountInDEV (react-dom.development.js:23914:13)
    at invokeEffectsInDev (react-dom.development.js:26716:9)
    at legacyCommitDoubleInvokeEffectsInDEV (react-dom.development.js:26699:5)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:26680:7)
    at flushPassiveEffectsImpl (react-dom.development.js:26389:5)
    at flushPassiveEffects (react-dom.development.js:26313:14)
    at eval (react-dom.development.js:26050:9)
    at workLoop (scheduler.development.js:256:34)
    at flushWork (scheduler.development.js:225:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:534:21)
eval @ Account.tsx:10
commitHookEffectListMount @ react-dom.development.js:21035
invokePassiveEffectMountInDEV @ react-dom.development.js:23914
invokeEffectsInDev @ react-dom.development.js:26716
legacyCommitDoubleInvokeEffectsInDEV @ react-dom.development.js:26699
commitDoubleInvokeEffectsInDEV @ react-dom.development.js:26680
flushPassiveEffectsImpl @ react-dom.development.js:26389
flushPassiveEffects @ react-dom.development.js:26313
eval @ react-dom.development.js:26050
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
```

I've tried bunch of ways, even going around this by having the comlink.wrap outside of the react component, but then there are other issues especially around the fact that the worker's init is async. Is there a way to make it work in the similar fashion as the code provided? Thank you!

**Comment by chris-laplante** [comment]
Try this:

```typescript
setWorkerApi(() => workerApi);
```

instead of:

```typescript
setWorkerApi(workerApi);
```

I forget where I saw it, but apparently the proxy is treated as an updater function, rather than the value. So you explicitly pass an updater function that just returns the instance.

**Comment by pycan-jouza** [comment]
> Try this:

It's working. You've got to be kidding me. I've spent 2 days on this. I'm so grateful, thank you so much!!!

**Comment by chris-laplante** [comment]
> > Try this:
> 
> It's working. You've got to be kidding me. I've spent 2 days on this. I'm so grateful, thank you so much!!!

No problem :). I too have wasted many days on this stuff. Best of luck lol.
