### ISSUE TITLE
Cors Error in version 2.0

### ISSUE THREAD

**Issue by daniele-zurico** [GoogleChromeLabs/comlink#8]
Version: 2.0.0
Demo:
`index.html`
```
<!DOCTYPE html>
<iframe src="http://127.0.0.1:2001">
</iframe>
<script src="https://cdn.jsdelivr.net/npm/comlinkjs@2/comlink.global.min.js"></script>
<script>
  async function main() {
    const ifr = document.querySelector('iframe');
    await new Promise(resolve => ifr.onload = resolve);
    const api = Comlink.proxy(ifr.contentWindow);
    const instanceOfComunication = await api.Comunication.getInstance();
    console.log(await instanceOfComunication.counter);
    await instanceOfComunication.inc();
    console.log(await instanceOfComunication.counter);
  }
  main();
</script>
```
`iframe.html`
```
<!doctype html>
<script src="https://cdn.jsdelivr.net/npm/comlinkjs@2/comlink.global.min.js"></script>
<script>
let instance = null;
class Comunication {
  constructor() {
    this._counter = 0;
  }

  static getInstance() {
      if (!instance)
          instance = new Comunication();
      return Comlink.proxyValue(instance);
  }

  get counter() {
      return this._counter;
  }

  inc() {
      this._counter++;
  }
}
Comlink.expose({Comunication}, self.parent);
</script>
```

live-server index.html --cors --port=2000
live-server iframe.html --cors --port=2001

Error:
```
comlink.global.min.js:1 Uncaught DOMException: Blocked a frame with origin "http://127.0.0.1:2001" from accessing a cross-origin frame.
    at j (https://cdn.jsdelivr.net/npm/comlinkjs@2/comlink.global.min.js:1:1577)
    at Object.c [as expose] (https://cdn.jsdelivr.net/npm/comlinkjs@2/comlink.global.min.js:1:376)
    at http://127.0.0.1:2001/:24:9
j @ comlink.global.min.js:1
c @ comlink.global.min.js:1
(anonymous) @ (index):24
comlink.global.min.js:formatted:83 Uncaught (in promise) DOMException: Blocked a frame with origin "http://localhost:2000" from accessing a cross-origin frame.
    at j (https://cdn.jsdelivr.net/npm/comlinkjs@2/comlink.global.min.js:1:1577)
    at Object.a [as proxy] (https://cdn.jsdelivr.net/npm/comlinkjs@2/comlink.global.min.js:1:55)
    at main (http://localhost:2000/:9:25)
    at <anonymous>
```

```
function j(a) {
        return 'Window' === a.constructor.name
    }
```

**Comment by surma** [comment]
Fixed in v2.0.1 :) Thank for the issue
